apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    httpMethod: GET

- name: Loki
  type: loki
  access: proxy 
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  environment:
  - GF_SERVER_ROOT_URL=http://localhost:3002/
  - GF_SERVER_ALLOWED_ORIGINS=https://3002-cs-127602842404-default.cs-europe-west4-fycr.cloudshell.dev,http://localhost:3002
